name: Update Matches Data
on:
  schedule:
    - cron: '0 */3 * * *'  # كل 3 ساعات (تعدل حسب حاجتك)
  workflow_dispatch:       # يسمح بالتشغيل اليدوي

jobs:
  update-matches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # ضروري لعمل git push

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install requests

      - name: Fetch Latest Data
        env:
          FOOTBALL_API_KEY: ${{ secrets.FOOTBALL_API_KEY }}
        run: python .github/scripts/fetch-data.py

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add data/matches.json
          git diff --quiet && git diff --staged --quiet || git commit -m "Auto-update matches data [skip ci]"
          git push
