name: Update Matches
on:
  schedule:
    - cron: '0 */6 * * *'  # كل 6 ساعات
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Fetch Data
        env:
          FOOTBALL_API_KEY: ${{ secrets.FOOTBALL_API_KEY }}
        run: |
          curl -H "X-Auth-Token: $FOOTBALL_API_KEY" \
               "https://api.football-data.org/v4/matches" \
               > data/matches.json

      - name: Commit & Push
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add data/matches.json
          git commit -m "Auto-update matches data" || echo "No changes"
          git push
