name: Update Matches
on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch Data
        env:
          FOOTBALL_API_KEY: ${{ secrets.FOOTBALL_API_KEY }}
        run: |
          curl -H "X-Auth-Token: $FOOTBALL_API_KEY" \
               "https://api.football-data.org/v4/matches" \
               > data/matches.json

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

      - name: Commit & Push
        run: |
          git add data/matches.json
          git diff --quiet && git diff --staged --quiet || git commit -m "Auto-update matches data"
          git push
