name: Update Match Data
on:
  schedule:
- cron: '*/5 * * * *'  # كل 5 دقائق للاختبار  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Fetch New Data
        run: |
          pip install requests
          python .github/scripts/fetch-data.py
        env:
          API_KEY: ${{ secrets.FOOTBALL_API_KEY }}
          
      - name: Commit Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add data/matches.json
          git commit -m "Auto-update match data"
          git push
