name: Update Matches Data
on:
  schedule:
    - cron: '0 * * * *'  # كل ساعة
  workflow_dispatch:  # تشغيل يدوي

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: pip install requests
      
      - name: Fetch data
        env:
          FOOTBALL_API_KEY: ${{ secrets.FOOTBALL_API_KEY }}
        run: |
          python .github/scripts/fetch-data.py
          git config --global user.name 'Automated'
          git config --global user.email 'actions@users.noreply.github.com'
          git add data/matches.json
          git commit -m "Auto-update matches data [skip ci]"
          git push
